
version: '3.9'

services:
    mosquitto:
        image: eclipse-mosquitto:latest
        volumes:
            - ./config/mosquitto:/mosquitto
        ports:
            - 1883:1883
            - 9001:9001

    influxdb:
        image: influxdb:latest
        ports:
            - '8086:8086'
        volumes:
            - influxdb-storage:/var/lib/influxdb
        networks:
            - internal
        environment:
            - INFLUXDB_DB=${INFLUXDB_DB_NAME}
            - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
            - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
        restart: always
        
    chronograf:
        image: chronograf:latest
        ports:
            - '127.0.0.1:8888:8888'
        volumes:
            - chronograf-storage:/var/lib/chronograf
        networks:
            - internal
        depends_on:
            - influxdb
        environment:
            - INFLUXDB_URL=http://influxdb:8086
            - INFLUXDB_USERNAME=${INFLUXDB_USERNAME}
            - INFLUXDB_PASSWORD=${INFLUXDB_PASSWORD}
        restart: always

    grafana:
        image: grafana/grafana:latest
        ports:
            - '3000:3000'
        volumes:
            - grafana-storage:/var/lib/grafana
            - ./config/grafana/provisioning/:/etc/grafana/provisioning
        networks:
            - internal
        depends_on:
            - influxdb
        environment:
            - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
            - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
        restart: always
volumes:
    influxdb-storage:
    chronograf-storage:
    grafana-storage:

networks:
    internal:
        name: internal-net
