
version: '3.9'

services:
    mosquitto:
        image: eclipse-mosquitto:2.0.14
        volumes:
            - ./config/mosquitto:/mosquitto/config
            - mosquitto-storage:/mosquitto/data
        networks:
            - internal
        ports:
            - 1883:1883
            - 9001:9001
        restart: always

    influxdb:
        image: influxdb:2.2-alpine
        ports:
            - '8086:8086'
        volumes:
            - influxdb-storage:/var/lib/influxdb
        networks:
            - internal
        environment:
            - INFLUXDB_DB=${INFLUXDB_DB_NAME}
            - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
            - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
        restart: always
        
    chronograf:
        image: chronograf:1.9.4
        ports:
            - '127.0.0.1:8888:8888'
        volumes:
            - chronograf-storage:/var/lib/chronograf
        networks:
            - internal
        environment:
            - INFLUXDB_URL=http://influxdb:8086
            - INFLUXDB_USERNAME=${INFLUXDB_USERNAME}
            - INFLUXDB_PASSWORD=${INFLUXDB_PASSWORD}
        restart: always

    grafana:
        image: grafana/grafana:8.5.5
        ports:
            - '3000:3000'
        volumes:
            - grafana-storage:/var/lib/grafana
            - ./config/grafana/provisioning/:/etc/grafana/provisioning
        networks:
            - internal
        depends_on:
            - influxdb
        environment:
            - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
            - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
        restart: always

    mongo:
        image: mongo:5.0.9
        restart: always
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
            - MONGO_INITDB_DATABASE=${MONGO_DB_NAME}
        networks: 
            - internal
        volumes:
            - mongodb-storage:/data/db
        ports: 
            - 27017:27017

    mongo-express:
        image: mongo-express:0.54.0
        restart: always
        ports:
            - 8081:8081
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_USERNAME}
            - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_PASSWORD}
            - ME_CONFIG_MONGODB_SERVER=mongo
            - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
            - ME_CONFIG_BASICAUTH_USERNAME=${EXPRESS_USERNAME}
            - ME_CONFIG_BASICAUTH_PASSWORD=${EXPRESS_PASSWORD}
        networks: 
            - internal
        depends_on:
            - mongo
            
    https_proxy:
        image: 'jc21/nginx-proxy-manager:latest'
        restart: unless-stopped
        ports:
        - '80:80'
        - '81:81'
        - '443:443'
        volumes:
        - ./data:/data
        - ./letsencrypt:/etc/letsencrypt

volumes:
    influxdb-storage:
    chronograf-storage:
    grafana-storage:
    mosquitto-storage:
    mongodb-storage:

networks:
    internal:
        name: internal-net
