{
 "title": "default",
 "refresh": "25s",
 "panels": [
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"lomo\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"id\"] == \"${deviceId}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temp\")"
    }
   ]
  },
  {
   "title": "Soil",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 3, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"lomo\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"id\"] == \"${deviceId}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"soil\")"
    }
   ]
  },
  {
   "title": "Position",
   "type": "geomap",
   "gridPos": { "h": 10, "w": 4, "x": 11, "y": 0 },
   "targets": [
    {
     "query": "import \"strings\"\r\n\r\nfrom(bucket: \"lomo\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"id\"] == \"${deviceId}\")\r\n  |> group(columns: [\"lat_lon\"])\r\n  |> distinct(column: \"lat_lon\")\r\n  |> map(fn: (r) => {\r\n    parts = strings.split(v: r._value, t: \",\")\r\n    return {lat: parts[0], lon: parts[1]}\r\n  })"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"lomo\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"id\"] == \"${deviceId}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"hum\")"
    }
   ]
  }
 ]
}