#ifndef DEBUG_CONFIG_H
#define DEBUG_CONFIG_H

#define DEBUG_DEVICE_CONFIGURED true
#define DEBUG_DEVICE_ID "NONE"
#define DEBUG_DEVICE_NAME "NONE"
#define DEBUG_MIN_GAS_VALUE -1
#define DEBUG_MAX_GAS_VALUE -1
#define DEBUG_PROTOCOL_TYPE "NONE" 
#define DEBUG_PROXY_PORT -1
#define DEBUG_MQTT_PORT -1
#define DEBUG_TOKEN "NONE"
#define DEBUG_HOST "NONE"
#define DEBUG_SAMPLE_FREQUENCY 5
#define DEBUG_WIFI_SSID "NONE" 
#define DEBUG_WIFI_PASS "NONE"

#endif