#ifndef DEBUG_CONFIG_H
#define DEBUG_CONFIG_H

#define DEBUG_DEVICE_CONFIGURED true
#define DEBUG_DEVICE_ID "admin"
#define DEBUG_DEVICE_NAME "admin"
#define DEBUG_MIN_GAS_VALUE 40.00
#define DEBUG_MAX_GAS_VALUE 72.00
#define DEBUG_PROTOCOL_TYPE "MQTT" 
#define DEBUG_PROXY_PORT 9999
#define DEBUG_MQTT_PORT 1883
#define DEBUG_TOKEN "admin"
#define DEBUG_HOST "192.168.1.119"
#define DEBUG_SAMPLE_FREQUENCY 1
#define DEBUG_WIFI_SSID "D-Link-68A330" // FASTWEB-9224F1    -   Vodafone-C02090047  - D-Link-68A330
#define DEBUG_WIFI_PASS "KdmmFNak6p" // F2Z8NM741W   -    ERxFJfcyc3rtpY3H  -  KdmmFNak6p

#endif