apiVersion: 1
datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    editable: false
    secureJsonData:
      token: adminadminadmin
    jsonData:
      version: Flux
      organization: lomo
      defaultBucket: lomo
      tlsSkipVerify: true